### ISSUE TITLE
Main config file porting

### ISSUE THREAD

**Issue by alikindsys** [RORIdev/sisbase#33]
The `root` of the config.json from `1.0` is the `Data` of 2.0 and could easily be converted to.
### Example 1.0 Config file
```json
{
  "Token": "token",
  "MasterId": 123456789012345678,
  "PuppetId": [],
  "Prefixes": [
    "u!",
    "s!"
  ],
  "CustomSettings": {}
}
```
### Example 2.0 Config file
```json
{
  "Path": "C:\\Users\\roridev\\Development\\sisbase\\sisbase.Test\\bin\\Debug\\netcoreapp3.1/Config.json",
  "Data": {
    "Token": "token",
    "MasterId": 123456789012345678,
    "PuppetId": [],
    "Prefixes": ["s!"],
    "CustomSettings": {}
  }
}
```

**Comment by wffirilat** [comment]
Additional future-proofing:
Add a `ConfigVersion` attribute in the top level of the config file, for version detection if further updates are ever needed. For now, the ConfigVersion should probably be `2`, but keep in mind that it will not (necessarily) always match the package version. Make sure ConfigVersion is an *int* `2`, and not a string `"2.0.0"` or anything similar

**Comment by wffirilat** [comment]
Also, consider creating a backup of the old config file when auto-updating, for safety?
